name: MLflow CI
on: [push, pull_request]
permissions:
  contents: write
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Setup job
        run: echo "Memulai pipeline MLflow CI"

      - name: Run actions
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Check env
        run: |
          python --version
          echo "CSV_URL=${{ env.CSV_URL }}"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run MLflow project
        working-directory: Eksperimen_SML_Rudy_Eko/Workflow-CI
        run: mlflow run MLproject --env-manager=local --experiment-name "KDD Cyber Attack Classify - Tuning"

      - name: Get latest MLflow run_id
        continue-on-error: true
        run: |
          RUN_ID=$(ls -t Eksperimen_SML_Rudy_Eko/Workflow-CI/MLproject/mlruns/*/*/meta.yaml 2>/dev/null | head -1 | xargs dirname | xargs basename)
          echo "MLFLOW_RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

